<H1>
YOUTUBE SPAM COLLECTION
<H1>


In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import statsmodels.api as  sm
from sklearn.preprocessing import MinMaxScaler as mms
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn import metrics
import itertools

In [2]:
Data_Psy=pd.read_csv("C:/Users/venky kishore/Downloads/Youtube01-Psy.csv")
Data_Psy.head()

COMMENT_ID            AUTHOR  \
0  LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU         Julius NM   
1  LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A       adam riyati   
2  LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  Evgeny Murashkin   
3          z13jhp0bxqncu512g22wvzkasxmvvzjaz04   ElNino Melendez   
4          z13fwbwp1oujthgqj04chlngpvzmtt3r3dw            GsMega   

                  DATE                                            CONTENT  \
0  2013-11-07T06:20:48  Huh, anyway check out this you[tube] channel: ...   
1  2013-11-07T12:37:15  Hey guys check out my new channel and our firs...   
2  2013-11-08T17:34:21             just for test I have to say murdev.com   
3  2013-11-09T08:28:43   me shaking my sexy ass on my channel enjoy ^_^    
4  2013-11-10T16:05:38            watch?v=vtaRGgvGtWQ   Check this out .   

   CLASS  
0      1  
1      1  
2      1  
3      1  
4      1

In [3]:
Data_Katty=pd.read_csv("C:/Users/venky kishore/Downloads/Youtube02-KatyPerry.csv")
Data_Katty.head()

COMMENT_ID        AUTHOR                 DATE  \
0      z12pgdhovmrktzm3i23es5d5junftft3f   lekanaVEVO1  2014-07-22T15:27:50   
1    z13yx345uxepetggz04ci5rjcxeohzlrtf4      Pyunghee  2014-07-27T01:57:16   
2  z12lsjvi3wa5x1vwh04cibeaqnzrevxajw00k    Erica Ross  2014-07-27T02:51:43   
3    z13jcjuovxbwfr0ge04cev2ipsjdfdurwck  Aviel Haimov  2014-08-01T12:27:48   
4  z13qybua2yfydzxzj04cgfpqdt2syfx53ms0k    John Bello  2014-08-01T21:04:03   

                                             CONTENT  CLASS  
0  i love this so much. AND also I Generate Free ...      1  
1  http://www.billboard.com/articles/columns/pop-...      1  
2  Hey guys! Please join me in my fight to help a...      1  
3  http://psnboss.com/?ref=2tGgp3pV6L this is the...      1  
4  Hey everyone. Watch this trailer!!!!!!!!  http...      1

In [4]:
Data_Lmfao=pd.read_csv("C:/Users/venky kishore/Downloads/Youtube03-LMFAO.csv")
Data_Lmfao.head()

COMMENT_ID        AUTHOR  \
0  z13uwn2heqndtr5g304ccv5j5kqqzxjadmc0k  Corey Wilson   
1  z124jvczaz3dxhnbc04cffk43oiugj25yzo0k   Epic Gaming   
2      z13tczjy5xj0vjmu5231unho1ofey5zdk     LaS Music   
3  z13tzr0hdpnayhqqc04cd3zqqqjkf3ngckk0k    Cheryl Fox   
4  z12pcvix4zedcjvyb04ccr1r0mr2g5xwyng0k    PATRICK_TW   

                         DATE  \
0  2015-05-28T21:39:52.376000   
1  2015-05-28T20:07:20.610000   
2  2015-05-28T19:23:35.355000   
3  2015-05-28T17:49:35.294000   
4  2015-05-28T16:28:26.818000   

                                             CONTENT  CLASS  
0  <a href="http://www.youtube.com/watch?v=KQ6zr6...      0  
1                                   wierd but funny      0  
2  Hey guys, I&#39;m a human.<br /><br /><br />Bu...      1  
3       Party Rock....lol...who wants to shuffle!!!      0  
4                                        Party rock      0

In [5]:
Data_Eminen=pd.read_csv("C:/Users/venky kishore/Downloads/Youtube04-Eminem.csv")
Data_Eminen.head()

COMMENT_ID         AUTHOR  \
0    z12rwfnyyrbsefonb232i5ehdxzkjzjs2    Lisa Wellas   
1  z130wpnwwnyuetxcn23xf5k5ynmkdpjrj04   jason graham   
2    z13vsfqirtavjvu0t22ezrgzyorwxhpf3     Ajkal Khan   
3  z12wjzc4eprnvja4304cgbbizuved35wxcs  Dakota Taylor   
4    z13xjfr42z3uxdz2223gx5rrzs3dt5hna    Jihad Naser   

                         DATE  \
0                         NaN   
1  2015-05-29T02:26:10.652000   
2                         NaN   
3  2015-05-29T02:13:07.810000   
4                         NaN   

                                             CONTENT  CLASS  
0          +447935454150 lovely girl talk to me xxx      1  
1    I always end up coming back to this song<br />      0  
2  my sister just received over 6,500 new <a rel=...      1  
3                                              Cool      0  
4                     Hello I&#39;am from Palastine      1

In [6]:
Data_Shakira=pd.read_csv("C:/Users/venky kishore/Downloads/Youtube05-Shakira.csv")
Data_Shakira.head()

COMMENT_ID                              AUTHOR  \
0    z13lgffb5w3ddx1ul22qy1wxspy5cpkz504                          dharma pal   
1      z123dbgb0mqjfxbtz22ucjc5jvzcv3ykj                       Tiza Arellano   
2  z12quxxp2vutflkxv04cihggzt2azl34pms0k  Prìñçeśś Âliś Łøvê Dømíñø Mâđiś™    
3      z12icv3ysqvlwth2c23eddlykyqut5z1h                       Eric Gonzalez   
4      z133stly3kete3tly22petvwdpmghrlli                       Analena López   

                         DATE  \
0  2015-05-29T02:30:18.971000   
1  2015-05-29T00:14:48.748000   
2  2015-05-28T21:00:08.607000   
3  2015-05-28T20:47:12.193000   
4  2015-05-28T17:08:29.827000   

                                             CONTENT  CLASS  
0                                         Nice song      0  
1                                      I love song       0  
2                                      I love song       0  
3  860,000,000 lets make it first female to reach...      0  
4                      shakira is best for worldcup      0

In [7]:
Youtube=Data_Psy.append([Data_Katty,Data_Lmfao,Data_Eminen,Data_Shakira],ignore_index=True)

In [8]:
Youtube.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1956 entries, 0 to 1955
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   COMMENT_ID  1956 non-null   object
 1   AUTHOR      1956 non-null   object
 2   DATE        1711 non-null   object
 3   CONTENT     1956 non-null   object
 4   CLASS       1956 non-null   int64 
dtypes: int64(1), object(4)
memory usage: 76.5+ KB


In [9]:
Youtube.head()

COMMENT_ID            AUTHOR  \
0  LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU         Julius NM   
1  LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A       adam riyati   
2  LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  Evgeny Murashkin   
3          z13jhp0bxqncu512g22wvzkasxmvvzjaz04   ElNino Melendez   
4          z13fwbwp1oujthgqj04chlngpvzmtt3r3dw            GsMega   

                  DATE                                            CONTENT  \
0  2013-11-07T06:20:48  Huh, anyway check out this you[tube] channel: ...   
1  2013-11-07T12:37:15  Hey guys check out my new channel and our firs...   
2  2013-11-08T17:34:21             just for test I have to say murdev.com   
3  2013-11-09T08:28:43   me shaking my sexy ass on my channel enjoy ^_^    
4  2013-11-10T16:05:38            watch?v=vtaRGgvGtWQ   Check this out .   

   CLASS  
0      1  
1      1  
2      1  
3      1  
4      1

In [10]:
Youtube.tail()

COMMENT_ID                AUTHOR  \
1951  _2viQ_Qnc6-bMSjqyL1NKj57ROicCSJV5SwTrw-RFFA          Katie Mettam   
1952  _2viQ_Qnc6-pY-1yR6K2FhmC5i48-WuNx5CumlHLDAI  Sabina Pearson-Smith   
1953  _2viQ_Qnc6_k_n_Bse9zVhJP8tJReZpo8uM2uZfnzDs         jeffrey jules   
1954  _2viQ_Qnc6_yBt8UGMWyg3vh0PulTqcqyQtdE7d4Fl0        Aishlin Maciel   
1955  _2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA           Latin Bosch   

                            DATE  \
1951  2013-07-13T13:27:39.441000   
1952  2013-07-13T13:14:30.021000   
1953  2013-07-13T12:09:31.188000   
1954  2013-07-13T11:17:52.308000   
1955  2013-07-12T22:33:27.916000   

                                                CONTENT  CLASS  
1951  I love this song because we sing it at Camp al...      0  
1952  I love this song for two reasons: 1.it is abou...      0  
1953                                                wow      0  
1954                            Shakira u are so wiredo      0  
1955                         Shakira is the best dancer      0

In [11]:
Youtube.iloc[1750:1850]

COMMENT_ID               AUTHOR  \
1750        z13szlz5sp2zw3fxc04cc3nbhlmjxnphivg0k        Robloxia Asap   
1751          z133vdcgmrijgrhld22zst0i2nfnvdvxa04               How To   
1752        z13twxvoxwz1f11pk04cij1b0zi1ifbhdno0k         mariam shoja   
1753          z134zb2xvybxwt54s04cexswtliatpbqxjs          Marius Dima   
1754            z12gj5gi4leawfcni225jty5wzvecj53m              Jet Lee   
...                                           ...                  ...   
1845  _2viQ_Qnc6_NswChsPPlG9Uf0ofpNvP1p2xoIoIi558       Mohammad Dorri   
1846  _2viQ_Qnc6-adCzTDLAhqNVQ5hFYcjPyPI5m7pHY4BY          Lizzy Molly   
1847  _2viQ_Qnc68Q2-t0ozy5t7pGOgxPEnJYsDVa48udRIQ             5000palo   
1848  _2viQ_Qnc6-jidHqOHj6hf4XnhflHNGicw4dL1vZRvQ         DizzyDank314   
1849  _2viQ_Qnc6_Z85BMDurr0H0sdfTiCwy1hAg5aytbkWg  Trulee IsNotAmazing   

                            DATE  \
1750  2015-04-25T19:54:03.298000   
1751  2015-04-25T06:38:00.463000   
1752  2015-04-23T10:14:34.527000   
1753  2015-04-23T09:27:06.888000   
1754  2015-04-23T08:08:38.925000   
...                          ...   
1845  2013-09-10T14:21:06.521000   
1846  2013-09-09T17:34:07.052000   
1847  2013-09-07T21:37:36.738000   
1848  2013-09-07T20:04:51.947000   
1849  2013-09-07T14:18:22.601000   

                                                CONTENT  CLASS  
1750  Could Spanish people understand this?<br /><br...      1  
1751  PLEASSSSSSSSSSSSSSSS SUBSCRIBEEEEEEEEEE MY CHA...      1  
1752                  Check out this video on YouTube:      1  
1753  New way to make money easily and spending 20 m...      1  
1754        There are beautiful songs please subscribe      1  
...                                                 ...    ...  
1845        please visit our web: wellcomemd.blogfa.com      1  
1846  PLEASE CHECK OUT MY VIDEO CALLED &quot;WE LOVE...      1  
1847                                     She is perfect      0  
1848           ｈｔｔｐ://ｗｗｗ.ｅｂａｙ.ｃｏｍ/ｕｓｒ/ｓｈｏｅｃｏｌｌｅｃｔｏｒ314      1  
1849             Beautiful song beautiful girl it works      0  

[100 rows x 5 columns]

In [12]:
Youtube.shape

(1956, 5)

In [13]:
Youtube.columns

Index(['COMMENT_ID', 'AUTHOR', 'DATE', 'CONTENT', 'CLASS'], dtype='object')

In [14]:
Youtube.describe()

CLASS
count  1956.000000
mean      0.513804
std       0.499937
min       0.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       1.000000

<H2>
DATA CLEANING AND EDA:
<H2>

<H2>
Comment
<H2>

In [15]:
Youtube.COMMENT_ID.isnull().sum()

0

In [16]:
Youtube.COMMENT_ID.describe()

count                                            1956
unique                                           1953
top       _2viQ_Qnc68fX3dYsfYuM-m4ELMJvxOQBmBOFHqGOk0
freq                                                2
Name: COMMENT_ID, dtype: object

In [17]:
Youtube.COMMENT_ID.value_counts()

_2viQ_Qnc68fX3dYsfYuM-m4ELMJvxOQBmBOFHqGOk0    2
LneaDw26bFuH6iFsSrjlJLJIX3qD4R8-emuZ-aGUj0o    2
LneaDw26bFvPh9xBHNw1btQoyP60ay_WWthtvXCx37s    2
LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU    1
LneaDw26bFsTytWDcS_4DFWlbxAlCfw2c_9PIcArNdw    1
                                              ..
z13qh3azhtvkvbypn04cflwaxoz5x51bip00k          1
z122g12wzuztdjac4232jxuomqylcfjhc04            1
z122ghagzyvyzrv3b23fzf4pelvusdoub              1
z13hhrvguty1drrkk23ie1ywjn31zj0sl              1
_2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA    1
Name: COMMENT_ID, Length: 1953, dtype: int64

<H2>
Author
<H2>

In [18]:
Youtube.AUTHOR.isnull().sum()

0

In [19]:
Youtube.AUTHOR.describe()

count      1956
unique     1792
top       M.E.S
freq          8
Name: AUTHOR, dtype: object

In [20]:
Youtube.AUTHOR.value_counts()

M.E.S              8
5000palo           7
Louis Bryant       7
Shadrach Grentz    7
DanteBTV           6
                  ..
Nick McGoldrick    1
Shaun Mac          1
Denzel Saimi       1
GX2re              1
Latin Bosch        1
Name: AUTHOR, Length: 1792, dtype: int64

<H2>
Date
<H2>

In [21]:
Youtube.DATE.describe()

count                           1711
unique                          1709
top       2013-10-05T00:57:25.078000
freq                               2
Name: DATE, dtype: object

In [22]:
Youtube.DATE.value_counts()

2013-10-05T00:57:25.078000    2
2014-11-07T19:33:46           2
2013-11-07T06:20:48           1
2014-07-21T11:05:51.945000    1
2015-05-28T21:50:26.114000    1
                             ..
2014-10-16T12:24:32           1
2014-10-16T12:21:58           1
2014-10-15T11:02:31           1
2014-10-15T05:15:27           1
2013-07-12T22:33:27.916000    1
Name: DATE, Length: 1709, dtype: int64

In [23]:
Youtube.DATE.isnull().sum()

245

In [24]:
null=Youtube.DATE.mode()

In [25]:
Youtube.DATE.fillna('null',inplace=True)

In [26]:
Youtube.DATE.isnull().sum()

0

<H2>
Content
<H2>

In [27]:
Youtube.CONTENT.describe()

count                                  1956
unique                                 1760
top       Check out this video on YouTube:
freq                                     97
Name: CONTENT, dtype: object

In [28]:
Youtube.CONTENT.value_counts()

Check out this video on YouTube:                                          97
Check out this playlist on YouTube:                                       21
Check Out The New Hot Video By Dante B Called Riled Up                      6
Shakira :-*                                                                 4
Like                                                                       4
                                                                           ..
;-)                                                                        1
HONESTLY, I WANNA SEE YOU BE BRAVE! oh wait...                             1
I LOVE YOU KATTY PERRY &lt;3                                               1
She is good. Does she make any more music? If she doesn't, she should!     1
Shakira is the best dancer                                                  1
Name: CONTENT, Length: 1760, dtype: int64

In [29]:
Youtube.CONTENT.isnull().sum()

0

<H2>
Class
<H2>

In [30]:
Youtube.CLASS.describe()

count    1956.000000
mean        0.513804
std         0.499937
min         0.000000
25%         0.000000
50%         1.000000
75%         1.000000
max         1.000000
Name: CLASS, dtype: float64

In [31]:
Youtube.CLASS.isnull().sum()

0

In [32]:
Youtube.CLASS.value_counts()

1    1005
0     951
Name: CLASS, dtype: int64

In [33]:
data_youtube=Youtube[['CONTENT','CLASS']]

In [34]:
data_youtube.head()

CONTENT  CLASS
0  Huh, anyway check out this you[tube] channel: ...      1
1  Hey guys check out my new channel and our firs...      1
2             just for test I have to say murdev.com      1
3   me shaking my sexy ass on my channel enjoy ^_^       1
4            watch?v=vtaRGgvGtWQ   Check this out .      1

In [35]:
data_youtube.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1956 entries, 0 to 1955
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   CONTENT  1956 non-null   object
 1   CLASS    1956 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 30.7+ KB


In [36]:
 data_youtube.describe()

CLASS
count  1956.000000
mean      0.513804
std       0.499937
min       0.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       1.000000

<H2>
Processing the content
<H2>

In [37]:
import re
re.findall("[A-Za-z]+","Hey22,What2 are4 you doing?")


['Hey', 'What', 'are', 'you', 'doing']

In [38]:
def process_content(content):
    return " ".join(re.findall("[A-Za-z]+",content.lower()))


In [39]:
data_youtube['REFORMED_CONTENT'] = data_youtube['CONTENT'].apply(process_content)


C:\Users\VENKYK~1\AppData\Local\Temp/ipykernel_9040/1380780338.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_youtube['REFORMED_CONTENT'] = data_youtube['CONTENT'].apply(process_content)


In [40]:
data_youtube.head()

CONTENT  CLASS  \
0  Huh, anyway check out this you[tube] channel: ...      1   
1  Hey guys check out my new channel and our firs...      1   
2             just for test I have to say murdev.com      1   
3   me shaking my sexy ass on my channel enjoy ^_^       1   
4            watch?v=vtaRGgvGtWQ   Check this out .      1   

                                    REFORMED_CONTENT  
0  huh anyway check out this you tube channel kob...  
1  hey guys check out my new channel and our firs...  
2             just for test i have to say murdev com  
3         me shaking my sexy ass on my channel enjoy  
4                 watch v vtarggvgtwq check this out

In [41]:
data_youtube.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1956 entries, 0 to 1955
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   CONTENT           1956 non-null   object
 1   CLASS             1956 non-null   int64 
 2   REFORMED_CONTENT  1956 non-null   object
dtypes: int64(1), object(2)
memory usage: 46.0+ KB


In [42]:
data_youtube.drop('CONTENT',axis=1,inplace=True)

F:\Anaconda\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


<H2>
Splitting into train and test
<H2>

In [43]:
x_train, x_test, y_train, y_test = train_test_split(data_youtube['REFORMED_CONTENT'],data_youtube['CLASS'],test_size=0.2,
                                                    random_state=57)

<H2>
Count vector for filtering of stopwords
<H2>

In [44]:
from sklearn.feature_extraction.text import CountVectorizer


In [45]:
count_vector = CountVectorizer(stop_words='english')
x_train_count = count_vector.fit_transform(x_train)


In [46]:
x_train_count.shape

(1564, 3345)

<H2>
Term Frequency Times Inverse Document Frequency
<H2>

In [47]:
from sklearn.feature_extraction.text import TfidfTransformer
tranformer = TfidfTransformer()
x_train_tfidf = tranformer.fit_transform(x_train_count)
x_train_tfidf.shape


(1564, 3345)

In [48]:
x_test_count = count_vector.transform(x_test)
x_test_count

<392x3345 sparse matrix of type '<class 'numpy.int64'>'
	with 2384 stored elements in Compressed Sparse Row format>

In [49]:
x_test_tfidf = tranformer.transform(x_test_count)
x_test_tfidf

<392x3345 sparse matrix of type '<class 'numpy.float64'>'
	with 2384 stored elements in Compressed Sparse Row format>

<H2>
MODEL SELECTION
<H2>

<H2>
Logistic Regression
<H2>

In [50]:
model_logistic = LogisticRegression()
model_logistic.fit(x_train_tfidf,y_train)


LogisticRegression()

In [51]:
model_logistic.score(x_train_tfidf,y_train)

0.9686700767263428

In [52]:
prediction_logistic = model_logistic.predict(x_test_tfidf)

In [53]:
confusion_matrix(y_test,prediction_logistic)

array([[176,   5],
       [ 24, 187]], dtype=int64)

In [54]:
print(classification_report(y_test,prediction_logistic))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92       181
           1       0.97      0.89      0.93       211

    accuracy                           0.93       392
   macro avg       0.93      0.93      0.93       392
weighted avg       0.93      0.93      0.93       392



<H2>
Random Forest
<H2>

In [55]:
model_randomforest = RandomForestClassifier()

In [56]:
model_randomforest.fit(x_train_tfidf,y_train)

RandomForestClassifier()

In [57]:
model_randomforest.score(x_train_tfidf,y_train)

0.9987212276214834

In [58]:
prediction_randomforest = model_randomforest.predict(x_test_tfidf)

In [59]:
confusion_matrix(y_test,prediction_randomforest)

array([[176,   5],
       [ 17, 194]], dtype=int64)

In [60]:
print(classification_report(y_test,prediction_randomforest))

              precision    recall  f1-score   support

           0       0.91      0.97      0.94       181
           1       0.97      0.92      0.95       211

    accuracy                           0.94       392
   macro avg       0.94      0.95      0.94       392
weighted avg       0.95      0.94      0.94       392



<H2>
Support Vector Classifier
<H2>

In [61]:
model_svc = SVC()

In [62]:
model_svc.fit(x_train_tfidf,y_train)

SVC()

In [63]:
model_svc.score(x_train_tfidf,y_train)

0.9948849104859335

In [64]:
prediction_svc = model_svc.predict(x_test_tfidf)

In [65]:
confusion_matrix(y_test,prediction_svc)

array([[175,   6],
       [ 22, 189]], dtype=int64)

In [66]:
print(classification_report(y_test,prediction_svc))

              precision    recall  f1-score   support

           0       0.89      0.97      0.93       181
           1       0.97      0.90      0.93       211

    accuracy                           0.93       392
   macro avg       0.93      0.93      0.93       392
weighted avg       0.93      0.93      0.93       392



<H2>
Ada Booster
<H2>

In [67]:
model_adabooster = AdaBoostClassifier()

In [68]:
model_adabooster.fit(x_train_tfidf,y_train)

AdaBoostClassifier()

In [69]:
model_adabooster.score(x_train_tfidf,y_train)

0.9680306905370843

In [70]:
prediction_adabooster = model_adabooster.predict(x_test_tfidf)

In [71]:
confusion_matrix(y_test,prediction_adabooster)

array([[176,   5],
       [ 20, 191]], dtype=int64)

In [72]:
print(classification_report(y_test,prediction_adabooster))

              precision    recall  f1-score   support

           0       0.90      0.97      0.93       181
           1       0.97      0.91      0.94       211

    accuracy                           0.94       392
   macro avg       0.94      0.94      0.94       392
weighted avg       0.94      0.94      0.94       392



<H2>
Gradient Booster
<H2>

In [73]:
model_gradientbooster = GradientBoostingClassifier()

In [74]:
model_gradientbooster.fit(x_train_tfidf,y_train)

GradientBoostingClassifier()

In [75]:
model_gradientbooster.score(x_train_tfidf,y_train)

0.9699488491048593

In [76]:
prediction_gradientbooster=model_adabooster.predict(x_test_tfidf)

In [77]:
confusion_matrix(y_test,prediction_gradientbooster)

array([[176,   5],
       [ 20, 191]], dtype=int64)

In [78]:
print(classification_report(y_test,prediction_gradientbooster))

              precision    recall  f1-score   support

           0       0.90      0.97      0.93       181
           1       0.97      0.91      0.94       211

    accuracy                           0.94       392
   macro avg       0.94      0.94      0.94       392
weighted avg       0.94      0.94      0.94       392

